// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBsEwq-w5dgg2x-u33jFLee-Ax7zjjPjk',
    appId: '1:483190907389:ios:05964df4176da88822f994',
    messagingSenderId: '483190907389',
    projectId: 'podcast-nikolay',
    databaseURL: 'https://podcast-nikolay.firebaseio.com',
    storageBucket: 'podcast-nikolay.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJpIvOfCwneNsxqKB5XJT61MRNr5srEZs',
    appId: '1:483190907389:web:355c8b36584b5b8922f994',
    messagingSenderId: '483190907389',
    projectId: 'podcast-nikolay',
    authDomain: 'podcast-nikolay.firebaseapp.com',
    databaseURL: 'https://podcast-nikolay.firebaseio.com',
    storageBucket: 'podcast-nikolay.firebasestorage.app',
    measurementId: 'G-C6EDN7218C',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJpIvOfCwneNsxqKB5XJT61MRNr5srEZs',
    appId: '1:483190907389:web:355c8b36584b5b8922f994',
    messagingSenderId: '483190907389',
    projectId: 'podcast-nikolay',
    authDomain: 'podcast-nikolay.firebaseapp.com',
    databaseURL: 'https://podcast-nikolay.firebaseio.com',
    storageBucket: 'podcast-nikolay.firebasestorage.app',
    measurementId: 'G-C6EDN7218C',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBsEwq-w5dgg2x-u33jFLee-Ax7zjjPjk',
    appId: '1:483190907389:ios:05964df4176da88822f994',
    messagingSenderId: '483190907389',
    projectId: 'podcast-nikolay',
    databaseURL: 'https://podcast-nikolay.firebaseio.com',
    storageBucket: 'podcast-nikolay.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFpwd8dbl2mvNOui3z5WV43lqKkW99j4o',
    appId: '1:483190907389:android:532b7134c458589522f994',
    messagingSenderId: '483190907389',
    projectId: 'podcast-nikolay',
    databaseURL: 'https://podcast-nikolay.firebaseio.com',
    storageBucket: 'podcast-nikolay.firebasestorage.app',
  );

}